# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "template-app-test"
client_id = "5d447b1b0763e93b1207a066ef31658a"
application_url = "https://violent-carried-font-valuable.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://violent-carried-font-valuable.trycloudflare.com/auth/callback",
  "https://violent-carried-font-valuable.trycloudflare.com/auth/shopify/callback",
  "https://violent-carried-font-valuable.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2023-07"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "cart-transform-bundles.myshopify.com"
