name: Deploy app
on:
  push:
    branches:
      - main
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
            fetch-depth: 0
      - name: Install Heroku CLI
        env:
          HEROKU_APP_NAME: ${{ vars.HEROKU_APP_NAME }}
          HEROKU_LOGIN_EMAIL: ${{ secrets.HEROKU_LOGIN_EMAIL }}
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: |
          curl https://cli-assets.heroku.com/install-ubuntu.sh | sh
          echo -e 'machine api.heroku.com\n login ${{ env.HEROKU_LOGIN_EMAIL }}\n password ${{ env.HEROKU_API_KEY }}\nmachine git.heroku.com\n login ${{ env.HEROKU_LOGIN_EMAIL }}\n password ${{ env.HEROKU_API_KEY }}' >> ~/.netrc
          heroku git:remote -a $HEROKU_APP_NAME
      - name: Deploy Heroku Webapp
        env:
            COMMIT_URL: ${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }}
        run: |
          git push --force heroku main:main
        
