name: Deploy app
on:
  push:
    branches:
      - main
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
            fetch-depth: 0
      - name: Install Shopify dependency
        run: |
          npm install -g shopify
      - name: Deploy Shopify App and Extensions
        env:
          SHOPIFY_CLI_PARTNERS_TOKEN: ${{ secrets.SHOPIFY_CLI_PARTNERS_TOKEN }} 
          COMMIT_URL: ${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }}
          SHOPIFY_API_KEY: ${{ secrets.SHOPIFY_API_KEY }}
        run:  | 
          npm run config:use production
          npm run deploy -- -f --source-control-url "$COMMIT_URL"
      - name: Install Heroku CLI
        env:
          HEROKU_LOGIN_EMAIL: ${{ secrets.HEROKU_LOGIN_EMAIL }}
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: |
          curl https://cli-assets.heroku.com/install-ubuntu.sh | sh
          echo -e 'machine api.heroku.com\n login $HEROKU_LOGIN_EMAIL\n password $HEROKU_API_KEY\nmachine git.heroku.com\n login $HEROKU_LOGIN_EMAIL\n password  $HEROKU_API_KEY' >> ~/.netrc
      - name: Deploy Heroku Webapp
        env:
            HEROKU_APP_NAME: ${{ vars.HEROKU_APP_NAME }}
            COMMIT_URL: ${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }}
        run: |
          heroku git:remote -a $HEROKU_APP_NAME
          git remote -v
          git config --global user.name loncaa
          git config --global user.email antonio@example.com
          git fetch
          git checkout main
          git commit --allow-empty -a -m "$COMMIT_URL"
          git push --force heroku main:main
        
